jobs:
  build:
    name: ${{ matrix.os }} JDK ${{ matrix.java-version }}.${{ matrix.distribution
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: ${{ matrix.distribution }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ matrix.gradle }}
    - continue-on-error: true
      name: Run Gradle
      run: gradle test nativeCompile --init-script build-scan-agree.gradle --scan
        --info --stacktrace
    - continue-on-error: true
      name: Upload wallet-tool as artifact
      uses: actions/upload-artifact@v4
      with:
        name: wallet-tool-${{ matrix.os }}-${{ matrix.java-version }}
        path: wallettool/build/native/nativeCompile/wallet-tool
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - graalvm-community
        gradle:
        - '8.8'
        java-version:
        - '17'
        - '21'
        os:
        - ubuntu-22.04
        - macOS-12
    timeout-minutes: 15
name: GraalVM Build
on:
  repository_dispatch:
    types: trigger-ga___graalvm.yml
